version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=pguser
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - 8001:8001
      - 6379:6379
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3050:80
  api:
    restart: always
    depends_on:
      - postgres
      - worker
    build:
      dockerfile: Dockerfile
      context: ./smartbrainapi
    ports:
      - 5000:5000
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    environment:
      - PGUSER=pguser
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  # client:
  #   stdin_open: true
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./client
  #   ports:
  #       - "3000:3000"

  client:
    stdin_open: true
    container_name: client
    build:
      context: ./smartbrainclient
      dockerfile: Dockerfile
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  worker:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: ./smartbrainml
    ports:
      - 2000:2000
    # volumes:
    #   - /app/node_modules
    #   - ./worker:/app
    environment:
        REDIS_HOST : redis
        REDIS_PORT: 6379
        REDIS_PWD: ''
        REDIS_SSL: 0
    links:
      - redis
      