apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: mosabami/smartbrainclient # update this to use the image in your registry eg <acrName>.azurecr.io/smartbrain/smartbrainclient
        ports:
        - containerPort: 3000
        env:
          - name: SERVER_URL
            value: server-service
          - name: WORKER_URL
            value: worker-service
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi