apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: mosabami/smartbrainapi:v11
        resources:
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-service
          - name:  REDIS_PORT
            value: '6379'
          - name: PGUSER
            value: guest
          - name: PGHOST
            value: postgres-service
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: smartbrain
          - name: PGPASSWORD
            value: guest
          - name: WORKER_URL
            value: worker-service


