apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: mosabami/smartbrainapi # update this to use the image in your registry eg <acrName>.azurecr.io/smartbrain/smartbrainapi:v1
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 5000
        env:
          - name: PGUSER
            value: guest
          - name: PGHOST
            value: postgres-service
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: smartbrain
          - name: PGPASSWORD
            value: guest
          - name: WORKER_URL
            value: worker-service


