apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
      - name: worker
        image: mosabami/smartbrainml # update this to use the image in your registry eg <acrName>.azurecr.io/smartbrain/smartbrainworker:v1
        ports:
        - containerPort: 2000
        env:
          - name: REDIS_HOST
            value: redis-service
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

